version: "3"
services:
  rasa_server:
    container_name: "rasa_server"
    build:
      context: .
    volumes:
      - "./:/app"
    ports:
      - "5005:5005"
    expose:
      - "5005"
  rasa_action_server:
    container_name: "rasa_action_server"
    build:
      context: actions
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    ports:
      - "5055:5055"
    expose:
      - "5055"
    depends_on:
      - rasa_server
