version: "3.0"
services:
  rasa:
    image: rasa/rasa:3.6.12-full
    restart: always
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: <image:tag>
    expose: 5055

  actions:
    image: rasa/rasa-sdk:latest
    restart: always
    volumes:
      - ./app/actions:/app/actions
    ports:
      - 5055
