# version: "3.6"
# services:
#   rasa:
#     image: rasa-bot:latest
#     build:
#       context: .
#       dockerfile: Dockerfile
#     restart: always
#     ports:
#       - 5005:5005
#     volumes:
#       - ./:/app

#   actions:
#     image: rasa-bot:latest
#     build:
#       context: .
#       dockerfile: actions/Dockerfile
#     restart: always
#     volumes:
#       - ./app/actions:/app/actions
#     ports:
#       - 5055
# version: "3.6"
# services:
#   rasa-server:
#     image: rasa-bot:latest
#     working_dir: /app
#     build: "./"
#     restart: always
#     volumes:
#       - ./actions:/app/actions
#       - ./data:/app/data
#     command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
#     ports:
#       - "5005:5005"
#     networks:
#       - all

#   rasa-actions-server:
#     image: rasa-bot:latest
#     working_dir: /app
#     build:
#       context: .
#       dockerfile: actions/Dockerfile
#     restart: always
#     volumes:
#       - ./actions:/app/actions
#       - ./utils:/app/utils
#     command: ["rasa", "run", "actions"]
#     ports:
#       - "5055:5055"
#     networks:
#       - all

# networks:
#   all:
#     driver: bridge
#     driver_opts:
#       com.docker.network.enable_ipv6: "true"

# version: "3"
# services:
#   nginx:
#     container_name: nginx
#     image: nginx
#     volumes:
#       - ./nginx:/etc/nginx/conf.d
#       - ./certs:/etc/letsencrypt/live/iantan.site
#     ports:
#       - 80:80
#       - 443:443
#     depends_on:
#       - rasa
#       - action_server
#   rasa:
#     container_name: "rasa_server"
#     build:
#       context: .
#     ports:
#       - "5005:5005"
#   action_server:
#     container_name: "rasa_action_server"
#     build:
#       context: actions
#     volumes:
#       - ./actions:/app/actions
#     ports:
#       - "5055:5055"

version: "3"
services:
  rasa:
    container_name: "rasa_server"
    build:
      context: .
    ports:
      - "5005:5005"
  action_server:
    container_name: "rasa_action_server"
    build:
      context: actions
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
